spring:
  servlet:
    multipart:
      maxFileSize: 1024MB
      maxRequestSize: 1024MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  # 数据源配置
  datasource:
#    # mysql8.0驱动要带cj 5.0不带cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro_video?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: 123456
    # mysql8.0驱动要带cj 5.0不带cj
    # 号称最快的连接池 默认
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间 默认10分钟 600000 ms
      idle-timeout: 1800000
      # 最大连接数 默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活 默认30分钟 1800000ms
      max-lifetime: 1800000
      # 连接超时时间，默认30秒 30000ms
      connection-timeout: 30000
      # 心跳机制 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
server:
  port: 8080
# mybatis-plus 配置
mybatis-plus:
  # 配置Mapper.xml 映射文件 单独把Mapper.xml 放在resource目录下的mapper目录
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置Mybatis 数据返回类型别名(默认别名是类名)
  type-aliases-package: edu.hhu.xulifeng.microvideo.pojo


